In [1]:
import pandas as pd

df=pd.read_csv(
    "data/Perovskite_Data.csv", low_memory=False 
)
print(df.shape)

(42851, 410)

In [ ]:
df.head(3) #display first 3 rows

,Ref_ID,Ref_ID_temp,Ref_name_of_person_entering_the_data,Ref_data_entered_by_author,Ref_DOI_number,Ref_lead_author,Ref_publication_date,Ref_journal,Ref_part_of_initial_dataset,Ref_original_filename_data_upload,...,Outdoor_PCE_Tse80,Outdoor_PCE_after_1000_h,Outdoor_power_generated,Outdoor_link_raw_data_for_outdoor_trace,Outdoor_detaild_weather_data_available,Outdoor_link_detailed_weather_data,Outdoor_spectral_data_available,Outdoor_link_spectral_data,Outdoor_irradiance_measured,Outdoor_link_irradiance_data
0,1,1,Adam Hultqvist,False,10.1021/jp5126624,Sabba et al.,06/01/2015,The Journal of Physical Chemistry C,True,Historic dataset on 2020 11 22_v7.xlsx,...,NaN,NaN,NaN,NaN,False,NaN,False,NaN,False,NaN
1,2,2,Adam Hultqvist,False,10.1021/jp5126624,Sabba et al.,06/01/2015,The Journal of Physical Chemistry C,True,Historic dataset on 2020 11 22_v7.xlsx,...,NaN,NaN,NaN,NaN,False,NaN,False,NaN,False,NaN
2,3,3,Adam Hultqvist,False,10.1021/jp5126624,Sabba et al.,06/01/2015,The Journal of Physical Chemistry C,True,Historic dataset on 2020 11 22_v7.xlsx,...,NaN,NaN,NaN,NaN,False,NaN,False,NaN,False,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42851 entries, 0 to 42850
Columns: 410 entries, Ref_ID to Outdoor_link_irradiance_data
dtypes: bool(37), float64(112), int64(10), str(251)
memory usage: 178.4 MB

In [28]:
#count the number of missing values in each column
miss_values = df.isna().sum()

#store columns with x missing values 
miss_columns = miss_values[miss_values > 30000]

#display the columns and how many values are missing in each
print(miss_columns)

Ref_free_text_comment                      41733
Cell_area_total                            41786
Cell_flexible_min_bending_radius           42851
Cell_semitransparent_AVT                   42842
Cell_semitransparent_raw_data              42838
                                           ...
Outdoor_power_generated                    42850
Outdoor_link_raw_data_for_outdoor_trace    42849
Outdoor_link_detailed_weather_data         42849
Outdoor_link_spectral_data                 42849
Outdoor_link_irradiance_data               42849
Length: 186, dtype: int64

In [ ]:
# Calculate the percentage of missing values
# only for the columns already stored in missing_columns
miss_percent = (
    df[miss_columns.index].isna().sum()
    / 42851
) * 100

# Display each selected column and its missing percentage
print(miss_percent)

Ref_free_text_comment                       97.390959
Cell_area_total                             97.514644
Cell_flexible_min_bending_radius           100.000000
Cell_semitransparent_AVT                    99.978997
Cell_semitransparent_raw_data               99.969662
                                              ...
Outdoor_power_generated                     99.997666
Outdoor_link_raw_data_for_outdoor_trace     99.995333
Outdoor_link_detailed_weather_data          99.995333
Outdoor_link_spectral_data                  99.995333
Outdoor_link_irradiance_data                99.995333
Length: 186, dtype: float64

In [30]:
# Remove every column that contains at least one missing value
df_clean = df.drop(columns=miss_columns.index)

# Display the cleaned dataset
df_clean.head()

,Ref_ID,Ref_ID_temp,Ref_name_of_person_entering_the_data,Ref_data_entered_by_author,Ref_DOI_number,Ref_lead_author,Ref_publication_date,Ref_journal,Ref_part_of_initial_dataset,Ref_original_filename_data_upload,...,Outdoor_installation_number_of_solar_tracking_axis,Outdoor_time_start,Outdoor_time_end,Outdoor_potential_bias_range,Outdoor_temperature_range,Outdoor_periodic_JV_measurements,Outdoor_PCE_burn_in_observed,Outdoor_detaild_weather_data_available,Outdoor_spectral_data_available,Outdoor_irradiance_measured
0,1,1,Adam Hultqvist,False,10.1021/jp5126624,Sabba et al.,06/01/2015,The Journal of Physical Chemistry C,True,Historic dataset on 2020 11 22_v7.xlsx,...,0,0000:00:00:00:00,0000:00:00:00:00,nan; nan,nan; nan,False,False,False,False,False
1,2,2,Adam Hultqvist,False,10.1021/jp5126624,Sabba et al.,06/01/2015,The Journal of Physical Chemistry C,True,Historic dataset on 2020 11 22_v7.xlsx,...,0,0000:00:00:00:00,0000:00:00:00:00,nan; nan,nan; nan,False,False,False,False,False
2,3,3,Adam Hultqvist,False,10.1021/jp5126624,Sabba et al.,06/01/2015,The Journal of Physical Chemistry C,True,Historic dataset on 2020 11 22_v7.xlsx,...,0,0000:00:00:00:00,0000:00:00:00:00,nan; nan,nan; nan,False,False,False,False,False
3,4,4,Adam Hultqvist,False,10.1021/jp5126624,Sabba et al.,06/01/2015,The Journal of Physical Chemistry C,True,Historic dataset on 2020 11 22_v7.xlsx,...,0,0000:00:00:00:00,0000:00:00:00:00,nan; nan,nan; nan,False,False,False,False,False
4,5,5,Adam Hultqvist,False,10.1021/jp5126624,Sabba et al.,06/01/2015,The Journal of Physical Chemistry C,True,Historic dataset on 2020 11 22_v7.xlsx,...,0,0000:00:00:00:00,0000:00:00:00:00,nan; nan,nan; nan,False,False,False,False,False

In [32]:
df_unknown = df_clean.copy() 
df_unknown = df_unknown.replace("Unknown", pd.NA)
miss_values_unknown = df_unknown.isna().sum()

miss_columns_unknown=miss_values_unknown[miss_values_unknown > 30000]
print(miss_columns_unknown)

Substrate_deposition_procedure                        41625
ETL_additives_compounds                               37173
ETL_deposition_aggregation_state_of_reactants         40626
ETL_deposition_synthesis_atmosphere                   41071
ETL_deposition_solvents                               40848
                                                      ...
JV_storage_atmosphere                                 42512
Stability_light_cycling_times                         42843
Stability_temperature_cycling_times                   42843
Stability_atmosphere                                  36128
Stability_periodic_JV_measurements_time_between_jv    42569
Length: 109, dtype: int64